apiVersion: v1
kind: Service
metadata:
  name: leadmangment
  labels:
    app: leadmangment
spec:
  selector:
    app: leadmangment
    type: LoadBalancer
  
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 31000

     
