apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpachat
  labels:
    app: leadmangment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leadmangment
  template:
    metadata:
      labels:
        app: leadmangment
    spec:
      containers:
<<<<<<< HEAD:App-Back-end/tpachat-deploy.yaml
        - image: maammar/tpachato:105
=======
        - image: maammar/leadmangment:latest
>>>>>>> bc9e234 (manifest uptated):App-Back-end/leadmangment.yaml
          name: tpachat        
          ports:
          - containerPort: 8089 
          env:
            - name: MYSQL_USER_NAME
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/leadmangment?useSSL=false                          
            - name: MYSQL_DATABASE
              value: leadmangment
            - name: MYSQL_ROOT_PASSWORD
              value: root
      imagePullSecrets:
      - name: regcred

     
