FROM jenkins/jenkins:latest

USER root

# Update package repositories and install wget
RUN apt-get update && \
    apt-get install -y wget

# Install JDK
RUN apt-get install -y openjdk-11-jdk

# Install Maven
ENV MAVEN_VERSION=3.8.8
RUN wget -O /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -xzf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt && \
    ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven && \
    rm /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz

# Set environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV MAVEN_HOME=/opt/maven
ENV PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin

USER jenkins