apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
     
      securityContext:
       runAsUser: 0


      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock    
         
      containers:
        - name: jenkins
          image: maammar/jenkis
          
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5000
              name: jnlpport
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home    
            - name: docker-socket
              mountPath: /var/run/docker.sock  
      imagePullSecrets:
          - name: regcred    
         