apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:

      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc
         
      containers:
        - name: jenkins
          image: maammar/jenkins
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5000
              name: jnlpport
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home    
      imagePullSecrets:
          - name: regcred    
         