apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  