apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  type: LoadBalancer  
  ports:
   - protocol: TCP
     port: 9000
     targetPort: 9000
     nodePort: 31000
